apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dse-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: datastax.com/v1alpha1
kind: DseDatacenter
metadata:
  name: dc-1
spec:
  dseClusterName: demo-cluster
  size: 1
  repository: datastaxlabs/dse-k8s-server
  version: 6.8.0-20190822
  storageclaim:
    storageclassname: dse-storage
    resources:
      requests:
        storage: 20Gi
  racks:
    - name: rack-1
  config:
    dse-yaml:
      authentication_options:
        enabled: False
    cassandra-yaml:
      num_tokens: 16
    # jvm-options:
    #  initial_heap_size: "4g"
    #  max_heap_size: "4g"
    10-write-prom-conf:
     enabled: True